version: 2.1
jobs:
  build:
    macos: 
      xcode: 14.0.1
    steps:
      - checkout
      - run:
          name: set scheme
          command: |
            scheme_list=$(xcodebuild -list -json -project Ironlog.iOS/Ironlog.xcodeproj/ | tr -d "\n")
            default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
            echo $default | cat >default
            echo Using default scheme: $default
      - run: ~/Project/build/build.sh