version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build-and-test:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  release-beta:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: release_internal_beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
  release-appstore:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: release_appstore
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
  testflight-release:
    jobs:
      - release-beta:
          filters:
            branches:
              only:
                - main
  appstore-release:
    jobs:
      - hold:
          type: approval
      - release-appstore:
          requires:
            - hold