version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:

  run-tests:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  build-for-appstore:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: build_for_appstore
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - persist_to_workspace:
          root: output
          paths:
            - "gym"

  release-testflight:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: release_testflight
    shell: /bin/bash --login -o pipefail
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  release-appstore:
    macos: 
      xcode: 14.0.1
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: release_appstore
    shell: /bin/bash --login -o pipefail
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-test:
    jobs:
      - run-tests
      - build-for-appstore:
          requires:
            - run-tests
          filters:
            branches:
              only:
                - main

      - release-testflight:
          requires:
            - build-for-appstore
          filters:
            branches:
              only:
                - main

      - release-appstore:
          filters:
            branches:
              only:
                - main