# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Build and run tests"
  lane :test do
    scan(
      include_simulator_logs: false
    )
  end

  desc "Push a new release to Testflight internal beta"
  lane :release_internal_beta do
  app_store_connect_api_key
  match(type: "appstore", git_url: "git@github.com:bstauff/Ironlog.certs.git")
  increment_build_number(
    xcodeproj: "Ironlog.xcodeproj",
    build_number: "$CIRCLE_BUILD_NUM")
  build_app(scheme: "Ironlog", export_method: "app-store")
  upload_to_testflight(
    skip_waiting_for_build_processing: true, 
    groups: ["Dev testing"],
    distribute_external: false)
  end
end
